### ISSUE TITLE
Ability to add/remove projects from the UI

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#10]
Currently, the app shows a list of projects based on flat json file.

This is to allow adding and removing of projects using the UI.

**Comment by Prateek93a** [comment]
Can I work on this for the Hacktoberfest contest?

**Comment by haroon-sheikh** [comment]
@Prateek93a Go ahead mate.

**Comment by Prateek93a** [comment]
@haroon-sheikh Thanks

**Comment by Prateek93a** [comment]
@haroon-sheikh Sir, how would you like the add project feature to be? Should there be a search button to search for the project and add them? Or should there be a dropdown to select the projects we want to see?

**Comment by haroon-sheikh** [comment]
@Prateek93a To search for the project from github and (if exists) add to the list of projects to show the commit status.

**Comment by Prateek93a** [comment]
@haroon-sheikh Ok

**Comment by Prateek93a** [comment]
@haroon-sheikh Sir, just wanted to confirm, that after adding or removing the repos, should the changes be made in the json file as well, or only the display should change?

**Comment by haroon-sheikh** [comment]
display is enough, the json is just a list of default projects.

**Comment by Prateek93a** [comment]
@haroon-sheikh Ok

**Comment by Prateek93a** [comment]
@haroon-sheikh I have made the PR, sorry I did not reference the issue along with it.
