### ISSUE TITLE
Make github login prettier

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#103]
Currently the initial github login page isn't responsive on mobiles.

![image](https://github.com/sitture/commit-status/assets/13623227/4d2f827e-0008-490b-92bb-c307af481a39)

Tasks

- [ ] Update styling to make login module prettier
- [ ] Update application title to `commit-status`

**Comment by Priyankaa2503** [comment]
Hello! I can give it a try. Could you assign it to me?

**Comment by Priyankaa2503** [comment]
Hello, just had a doubt i have made the page responsive for mobile screens and updated the title.
Also made few minor changes in UI of the login page. I have attached the screenshot too. Are any more changes required?
<img width="1439" alt="Screenshot 2023-10-01 at 12 24 17 PM" src="https://github.com/sitture/commit-status/assets/111295843/71420d00-9d86-44a8-84f0-3ee7bb10bada">

**Comment by haroon-sheikh** [comment]
Hi @Priyankaa2503, that should be enough for this issue. Thanks.

**Comment by Priyankaa2503** [comment]
Okay, thanks.

**Comment by Priyankaa2503** [comment]
Hello, just wanted to know if this PR would be hacktoberfest valid since it's my first time contributing. Thanks
