### ISSUE TITLE
When refreshing the page, the projects list is getting reset.

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#16]
Currently, we can add or remove to the list of projects. However, it resets when refreshing the page.

This is to tackle not resetting the projects list to default.

**Comment by ffeliks** [comment]
You can't write a file in a browser environment to the user's machine in any major browser. Libraries such as `fs` are supposed to be run in a Node.js environment.

**Comment by haroon-sheikh** [comment]
@ffeliks Yes that would be plan going ahead but for now, we just need to make use of the browser local storage to store the list of projects.

**Comment by ffeliks** [comment]
I'd like to work on this

**Comment by haroon-sheikh** [comment]
Go ahead @ffeliks, let me know if you have any questions.
