### ISSUE TITLE
Cannot remove projects when clicking on remove

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#17]
When clicking on `Remove` button, the project should be removed.

It's currently not doing that, but opens up the accordian instead.

**Comment by MeisterRed** [comment]
Hi, may I have a look and see if I can fix this bug?

**Comment by haroon-sheikh** [comment]
Go ahead @MeisterRed..

**Comment by MeisterRed** [comment]
Hopefully it's not too late but I've provided a solution to the issue
