### ISSUE TITLE
Add ability to filter by status of the projects

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#21]
## Add ability to filter by status of the projects

- Add a tabbed view to filter projects by `All/Unhealthy`
- All shows a full list of projects
- Unhealthy shows list of failed projects only

**Example:**
![image](https://user-images.githubusercontent.com/13623227/67040298-1ded1b00-f11b-11e9-99a8-1843717915b7.png)

**Comment by macanrox** [comment]
Can I take a stab at this?

**Comment by haroon-sheikh** [comment]
Yes @macanrox, go for it.

**Comment by haroon-sheikh** [comment]
@macanrox How you getting on with this?

**Comment by macanrox** [comment]
@haroon-sheikh Sorry for the lack of updates. It's been busy on my end. 
**Check out this update and let me know if there's anything that could be improved on.**

---
![cs-tab](https://user-images.githubusercontent.com/3775085/67428700-46a26400-f5a4-11e9-8f46-cb84aee6b3bc.gif)

So far there's the tabbed view buttons and spaghetti/skeleton code for the Filter component. I'll have a PR either later tonight or tomorrow.

**Comment by haroon-sheikh** [comment]
Hey @macanrox, thats looking really good. Exactly, what we're looking for.
