### ISSUE TITLE
Display an error test when project does not exist

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#22]
When adding a new project which does not exist. E.g. `invalid/invalid`, an error text should show `The 'invalid/invalid' project does not exist!`

**Comment by shravan-balasubramanian** [comment]
I will do this

**Comment by shravan-balasubramanian** [comment]
About the authorization part, where to add the github token and whose github token should be added. The Readme lacks those infos

**Comment by haroon-sheikh** [comment]
@shravan-balasubramanian please set it as an environment variable for your testing.. i.e. `export REACT_APP_GITHUB_TOKEN="token your-token"`

there's a further ticket https://github.com/sitture/commit-status/issues/8 to resolve this.

**Comment by shravan-balasubramanian** [comment]
If am not wrong, I think this is the right endpoint list all repos : https://api.github.com/users/{user-name}/repos. The code always returns a 404 :(. Please correct and help me if am wrong. Even the example site returns a 404. I am really interested to work on this issue
<img width="1440" alt="Screenshot 2019-10-19 at 8 43 33 PM" src="https://user-images.githubusercontent.com/46365868/67147289-3858fd00-f2b1-11e9-83ec-230ebb4f0580.png">
<img width="1440" alt="Screenshot 2019-10-19 at 8 43 33 PM" src="https://user-images.githubusercontent.com/46365868/67147295-4f97ea80-f2b1-11e9-835f-c17858d6a387.png">

**Comment by haroon-sheikh** [comment]
Try `https://api.github.com/repos/sitture/commit-status/statuses/master` would return you the `state` of the latest commit.
