### ISSUE TITLE
Clicking on the project link should not expand the accrodian

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#24]
Currently, when clcking on the project link, the accrodian expands also, that should only happen when clicking in the project row.

TODO:
- [ ] clicking on project link, does not open accrodian
- [ ] projects are opened in a new tab.

**Comment by adin234** [comment]
[PR](https://github.com/sitture/commit-status/pull/26) created

**Comment by haroon-sheikh** [comment]
Fixed by #26
