### ISSUE TITLE
Fix and issue with image not found

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#35]
https://sitture.github.io/commit-status/plus.svg is erroring which is used inside the Add bar. Update the references so that it can resolve properly.

**Comment by korczynsk1** [comment]
Hi @haroon-sheikh could you assign it to me? Thanks 🙇

**Comment by varadpoddar** [comment]
Whoops, I already created a PR 😅

**Comment by korczynsk1** [comment]
No problem :)
