### ISSUE TITLE
Add an input method to choose the auto refresh interval

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#44]
A way to set the interval in seconds (top right), which sets `authoRefreshIntervalId` in the ProjectList component state.

**Comment by Qoyyuum** [comment]
What did you mean by top right? Next to the input box or the most top right corner of the app?

**Comment by haroon-sheikh** [comment]
@Qoyyuum Top right corner of the app.

**Comment by ffeliks** [comment]
Seems that this issue was not resolved. I've created a new PR to address this issue https://github.com/sitture/commit-status/pull/59

**Comment by haroon-sheikh** [comment]
Fixed in #59.
