### ISSUE TITLE
Fix the deprecation warning "componentWillMount has been renamed"

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#45]
Following deprecation warning is thrown when running the application:

![image](https://user-images.githubusercontent.com/13623227/67764264-7d172d80-fa41-11e9-8587-fc789d80fd27.png)

Further details on async rendering https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by SafaElmali** [comment]
In which file you are using componentWillMount? Could you please give information about this?

**Comment by gabrielbs** [comment]
@SafaElmali This warning was on Helmet, I had this problem and once and had to change to helmet-async, that is compatible with react 16+

**Comment by Qoyyuum** [comment]
Error doesn't exist when I run the application. Other instances of component mounting are: `componentDidMount` and `componentWillUnmount` in `ProjectDetails.js` and `ProjectList.js`.

**Comment by haroon-sheikh** [comment]
@SafaElmali Yep the files I'm referring to are ProjectList.js and ProjectDetails.js
