### ISSUE TITLE
Update to literal word `Remove` to replace with `x` icon

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#61]
### Task

Currenty, to remove a project from the list, you have to click on the word `Remove`.

![image](https://user-images.githubusercontent.com/13623227/95018393-58670500-0657-11eb-94ac-9c18f4dadc48.png)

- [ ] Change the `Remove` to ❌ icon

**Comment by abhishekjain35** [comment]
I would like to work on this. If you could assign it to me.
