### ISSUE TITLE
Include all sub-statuses of each project

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#7]
To show sub git commit statuses of each project.

**Comment by Prateek93a** [comment]
@haroon-sheikh Sir, may I know  more precisely about what all things you would like to be displayed with each project?

**Comment by haroon-sheikh** [comment]
@Prateek93a Just the name and status of each github commit sub-status.

**Comment by Prateek93a** [comment]
@haroon-sheikh Ok I will try it

**Comment by Prateek93a** [comment]
@haroon-sheikh Should I show the details along with the repo itself, or should there be a button with each repo, which when pressed, the repo commit details are made visible?
