### ISSUE TITLE
Add a github icon to link back to github repository

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#73]
## Task

- [ ] Add a github icon (top left) corner to link back to https://github.com/sitture/commit-status repo.

**Comment by ameybhavsar24** [comment]
Please assign it to me.

**Comment by ameybhavsar24** [comment]
![image](https://user-images.githubusercontent.com/28699912/95990730-831c3f00-0e49-11eb-9fe8-2afeba0d52a9.png)
Are you suggesting to add icon to the left of this title?

**Comment by haroon-sheikh** [comment]
@ameybhavsar24 I actually meant on top of the page (not each project row) which links back to this repository. I guess we could add icons to each row also.

**Comment by ameybhavsar24** [comment]
Got it. As in to add a reference back to the main GitHub repository.

**Comment by ameybhavsar24** [comment]
>guess we could add icons to each row also.

I think that could be possible by fetching the owners' profile picture. Could you open a issue for that as well?

**Comment by haroon-sheikh** [comment]
@ameybhavsar24 Here you go https://github.com/sitture/commit-status/issues/75
