### ISSUE TITLE
Add Login with Github feature

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#74]
## Task

- [ ] Add the ability to login and authenticate with github

So that we can then use the oauth tokens to fetch the commit status

**Comment by asadkhalid305** [comment]
@haroon-sheikh in order to request access_token from GitHub we would need the server to call GitHub API since its payload requires client_secret which we cannot expose from the client side. What do you think about it?

**Comment by haroon-sheikh** [comment]
@asadkhalid305 We would need to create an oauth and set the client_id and client_secret as environment variables. Look at this for example https://levelup.gitconnected.com/how-to-implement-login-with-github-in-a-react-app-bd3d704c64fc

Please create an oauth app under your fork but leave it pickup these client_id and client_secret from env variables. Make sure you dont commit your details ;)

**Comment by asadkhalid305** [comment]
@haroon-sheikh I am glad for the article you shared. With some modifications I have made this feature more clear and precise. Now all you have to do is use access_token which is stored in localStorage to work further on the application. 

Please review [PR](https://github.com/sitture/commit-status/pull/78)

**Comment by asadkhalid305** [comment]
@haroon-sheikh I am hoping you review and merge the PR before Hacktoberfest ends.

**Comment by haroon-sheikh** [comment]
Fixed in #78
