### ISSUE TITLE
Add a project icon for each project.

### ISSUE THREAD

**Issue by haroon-sheikh** [sitture/commit-status#75]

**Comment by ameybhavsar24** [comment]
@haroon-sheikh Can you assign this to me?

**Comment by ameybhavsar24** [comment]
I am planning to use GitHub API to fetch `avatar_url`, for example `https://api.github.com/users/sitture`. Do you suggest any changes?

**Comment by haroon-sheikh** [comment]
Thats fine with me @ameybhavsar24. As long as both requests to get avatar and commit-status are async.
